### PR TITLE
Remove folks who have left, update titles

### PR DESCRIPTION
**Pull request by akegan**
Removed a few folks who have left, updated titles for Mariela and Bekah

### CODE REVIEW

**Review by aekong — APPROVED** [review]
this is one of those situations where i both approve and disapprove 😭

**Comment by akegan** [comment]
I reverted Bekah's role change for now because she said it's not HR official yet

**Comment by akegan** [comment]
@aekong I'll leave it to you to merge and deploy. I'm not sure how that works these days

**Comment by aekong** [comment]
thanks for updating 🤗

**Pull request merged**
