### PR TITLE
stop commenting the pantheon static site preview

### PR DESCRIPTION
**Pull request by aekong**

### CODE REVIEW

**Comment by akegan** [comment]
@aekong is this because vercel has gotten rid of the need for the comment bot?

**Comment by aekong** [comment]
Yeah, trying to remove unnecessary chatter

**Review by akegan — APPROVED** [review]
confirmed that the vercel link works. Looks like there might be some circleCI env vars that might not be needed anymore. If you haven't already, might be worth doing a pass to get rid of them if you haven't already?

**Comment by aekong** [comment]
yeah it's actually still building to gh pages and the pantheon static site, just getting rid of the comments.  thought i'd keep it around until we've figured out where exactly we host the ds site.

**Pull request merged**
