### PR TITLE
Adding Claire, Christina and Lorena to our team site

### PR DESCRIPTION
**Pull request by skinnylatte**

### CODE REVIEW

**Comment by akegan** [comment]
should we check to see if any of them want to share twitter handles?

**Comment by skinnylatte** [comment]
good point, i will ask

**Comment by skinnylatte** [comment]
@akegan only lorena wants to add her twitter. i have done that. i will merge this pr now

**Comment by skinnylatte** [comment]
once i fix a small formatting issue :)

**Comment by akegan** [comment]
@skinnylatte I assume that this is the small formatting issue! 
image

**Comment by skinnylatte** [comment]
Yes! Fixed it but had not pushed as I had to get on a call.

**Comment by akegan** [comment]
Christina's picture looks a bit stretched out horizontally but otherwise looks good. Not sure if that's something that you can solve

**Comment by skinnylatte** [comment]
I'll resize the image and try again

**Comment by skinnylatte** [comment]
This looks good, so I am going to merge. Happy Friday!

**Pull request merged**
